temperature: 0.0
max_final_answer_tokens: 2048
tags: UT
format: IND-Q
task: Rec
priming: false
generator_output: FA
evaluator_reasoning: DR
gpu_dispatch: tinker
icl_seed: 42
generator_models:
- qwen-3.0-30b
- gpt-oss-120b
model_names:
- qwen-3-30b_sft-as_qwen-3-30b_vs_gpt-oss-120b_AT_PW_ShareGPT
icl_count: 1
icl_model: gpt-oss-120b
icl_data_subset: english_26
icl_shuffle_per_sample: true
eval_dataset: sharegpt
eval_subset: english2_74
experiment_name: SGTR_05_trained-AT-PW_eval-on_all-OPs
mini_batch_name: qwen-3.0-30b_UT_IND_1shot_trained-std_ica-alt
