temperature: 1.0
max_final_answer_tokens: null

tags: "UT"
format: "PW-Q"
task: "Rec"
priming: False
generator_output: "FA"
evaluator_reasoning: "DR"

model_names: ['-set', 'eval_cot-r']
generator_models: ['-set', 'eval_cot-r_and_dr']
