temperature: 0.0
max_final_answer_tokens: 2048
tags: UT
format: PW-Q
task: Rec
priming: false
generator_output: FA
evaluator_reasoning: DR
gpu_dispatch: tinker
icl_seed: 42
generator_models:
- qwen-3.0-30b
- gpt-oss-120b
model_names:
- qwen-3.0-30b
icl_count: 1
icl_model: deepseek-3.1
icl_data_subset: english_26
icl_shuffle_per_sample: true
experiment_name: SGTR_02_trained-OP_eval-on_self-same-OP
mini_batch_name: qwen-3.0-30b_UT_PW_1shot_base_ica-ctrl
