temperature: 0.0
max_final_answer_tokens: 2048
tags: UT
format: PW-Q
task: Rec
priming: false
generator_output: FA
evaluator_reasoning: DR
gpu_dispatch: tinker
icl_seed: 42
generator_models:
- qwen-3.0-30b
- gpt-oss-120b
model_names:
- qwen-3-30b_sft-as_qwen-3-30b_vs_gpt-oss-120b_UT_PW_ShareGPT
icl_count: 10
icl_model: deepseek-3.1
icl_data_subset: english2_74
experiment_name: SGTR_01_trained-OP_eval-on_self-same-OP_ICA-unshuffled
mini_batch_name: qwen-3.0-30b_UT_PW_10shot_trained-std_ica-ctrl
